# Site settings
title: Coder's Coffee House
email: matthew.blott@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tech blog of Matthew Blott
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://coderscoffeehouse.com" # the base hostname & protocol for your site
twitter_username: matthewblott
github_username:  matthewblott

excerpt_separator: ""   # Workaround for http://blog.slaks.net/2013-08-09/jekyll-tag-was-never-closed
# highlighter: pygments

# Build settings
gems: ['jekyll-lunr-js-search', 'jekyll-assets', 'uglifier', 'jekyll-paginate', 'jekyll-paginate-category']
# markdown: kramdown

# highlighter: rouge

# kramdown:
#   input: GFM # for use with Github
#   syntax_highlighter: rouge

assets:
  compress:
    css:  sass
    js:   uglifier

#  sources:
#    - _assets/images
#    - _assets/javascripts
#    - _assets/stylesheets

paginate: 5
paginate_path: "/pages/:num/"
category_dir: "categories"
category_layout: "index.html"
