title: Coder's Coffee House
email: matthew.blott@gmail.com
description: Tech blog site and other things that interest me.
baseurl: ''
url: ''
twitter_username: matthewblott
github_username:  matthewblott
google_analytics: UA-77648562-1

defaults:
  -
    scope:
      path: "other"
      type: "posts"
    values:
      layout: "default"

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
