title: Coder's Coffee House
email: your-email@example.com
description: >- # this means to ignore newlines until 'baseurl:''
  Write an awesome description for your new site here.
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username:  jekyll

defaults:
  -
    scope:
      path: "other" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"

gems: [jekyll-assets, jekyll-paginate-v2, jekyll-seo-tag]

plugins:
  - jekyll-assets
  - jekyll-paginate-v2
  - jekyll-seo-tag

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail: 
    before: 2
    after: 2
  indexpage: 'index'